kind: Service
apiVersion: v1
metadata:
  name:  graphite-service
spec:
  selector:
    app:  graphite
  type:  LoadBalancer
  ports:
  - name: graphite-receiver-plaintext
    port: 2003
    targetPort: 2003
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: graphite
  name: graphite-service-internal
  namespace: default
spec:
  ports:
  - name: listengraphite
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: graphite
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
